# CREATE TABLE url (
#     id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100001),
#     key VARCHAR(6) NOT NULL,
#     value VARCHAR(256) NOT NULL,
#     PRIMARY KEY (id)
# );
# from sqlalchemy import create_engine
# from sqlalchemy.orm import sessionmaker
# from .main import app
# from . import models
# from .models import Base
# database_url=f"postgres://postgres:akash123@localhost:5431/postgres"
# engine=create_engine(database_url)
# TestingSessionLocal=sessionmaker(bind=engine,autocommit=False,autoflush=False)

# def override_get_db():
#     db=TestingSessionLocal()
#     try:
#         yield db
#     finally:
#         db.close()
# app.dependency_override[get_db]=override_get_db

# def client():
#     # models.Base.metadata.drop_all(bind=engine)
#     # models.Base.metadata.create_all(bind=engine)
#     yield TestClient(app)
# def test_get_url():
#     client=client()
#     res=client.get('/miniurl/2Bm')
#     print(res)